# Generated by Django 3.1.7 on 2021-03-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='botwTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('newsletter_campaign_id', models.CharField(blank=True, max_length=200, null=True)),
                ('newsletter_branding', models.CharField(choices=[('branding_botw', 'Best of the Week'), ('branding_bh', 'Gear Alert')], default='custom_field', max_length=25)),
                ('tile_location', models.CharField(max_length=200, null=True)),
                ('tile_headline', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Best of the Week Test',
                'verbose_name_plural': 'Best of the Week Test',
            },
        ),
    ]
