# Generated by Django 3.1.7 on 2021-03-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botwtest',
            old_name='tile_headline',
            new_name='tile_1_headline',
        ),
        migrations.RenameField(
            model_name='botwtest',
            old_name='tile_location',
            new_name='tile_1_location',
        ),
        migrations.AddField(
            model_name='botwtest',
            name='tile_2_headline',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='botwtest',
            name='tile_2_location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='botwtest',
            name='tile_3_headline',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='botwtest',
            name='tile_3_location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='botwtest',
            name='tile_4_headline',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='botwtest',
            name='tile_4_location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='botwtest',
            name='tile_5_headline',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='botwtest',
            name='tile_5_location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='botwtest',
            name='tile_6_headline',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='botwtest',
            name='tile_6_location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
