# Generated by Django 3.1.7 on 2021-03-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20210304_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botwtest',
            name='newsletter_campaign_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='botwtest',
            name='tile_1_headline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='botwtest',
            name='tile_1_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='botwtest',
            name='tile_2_headline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='botwtest',
            name='tile_2_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='botwtest',
            name='tile_3_headline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='botwtest',
            name='tile_3_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='botwtest',
            name='tile_4_headline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='botwtest',
            name='tile_4_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='botwtest',
            name='tile_5_headline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='botwtest',
            name='tile_5_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='botwtest',
            name='tile_6_headline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='botwtest',
            name='tile_6_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
