# Generated by Django 3.1.7 on 2021-03-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_auto_20210304_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botwtest',
            options={},
        ),
    ]
