# Generated by Django 3.1.7 on 2021-03-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_auto_20210305_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botwtest',
            options={'verbose_name': 'Best of the Week Test', 'verbose_name_plural': 'Best of the Week Test'},
        ),
    ]
